meta_product_name: "Kardsandmatch"
meta_title: "Kardsandmatch - Nobody to play with ?"
meta_description: "An app that allows to find people and places to play"
meta_image: "logo_karma.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account" # required for Twitter Cards
