meta_product_name: "Kardsandmatch"
 meta_title: "Kardsandmatch - An app that allows to find people and places to play"
 meta_description: "Nobody to play with ? Nowhere to play ?"
 meta_image: "cover.png" # should exist in `app/assets/images/`
 twitter_account: "@product_twitter_account" # required for Twitter Cards
